common:
    lid_topic:  "/livox/points"
    imu_topic:  "/livox/imu"
    time_sync_en: false
    time_offset_lidar_to_imu: 0.0


preprocess:
    lidar_type: 1
    scan_line: 6
    blind: 0.15

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    360
    det_range:     80.0
    extrinsic_est_en:  true
    extrinsic_T: [-0.062, 0.0, 0.042]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true
    dense_publish_en: false
    scan_bodyframe_pub_en: true
    frame_id: camera_init
    body_frame_id: mid360_imu_link
    child_frame_id: base
    body_to_child_t: [-0.28, 0.0, -0.105]
    body_to_child_rpy: [0.0, 0.0, 0.0]

pcd_save:
    pcd_save_en: false
    interval: -1
