common:
    lid_topic: "/livox/points"
    imu_topic: "/livox/imu"
    con_frame: false
    con_frame_num: 1
    cut_frame: false
    cut_frame_time_interval: 0.1
    time_diff_lidar_to_imu: 0.0

frames:
    body: "base"

preprocess:
    lidar_type: 1
    scan_line: 6
    timestamp_unit: 1
    blind: 0.15
    det_range: 40.0


mapping:
    imu_en: true
    extrinsic_est_en: false
    imu_time_inte: 0.002
    lidar_time_inte: 0.1
    satu_acc: 35.0
    satu_gyro: 30.0
    acc_norm: 9.81
    lidar_meas_cov: 0.004
    acc_cov_output: 500
    gyr_cov_output: 1000
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    imu_meas_acc_cov: 0.08
    imu_meas_omg_cov: 0.08
    gyr_cov_input: 0.008
    acc_cov_input: 0.08
    plane_thr: 0.04
    match_s: 45
    ivox_grid_resolution: 0.3
    gravity: [0.0, 0.0, -9.81]
    gravity_init: [0.0, 0.0, -9.81]
    extrinsic_T: [-0.062, 0.0, 0.042]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

odometry:
    publish_odometry_without_downsample: false

publish:
    path_en: true
    scan_publish_en: true
    scan_bodyframe_pub_en: false

pcd_save:
    pcd_save_en: false
    interval: -1
