# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

go2/go2_handstand:
  model_name: "policy_1.pt"
  num_observations: 48
  observations: ["trot_phase", "zeros1", "ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [0]
  observations_history_priority: "time"
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,  # 动作裁剪下界
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,  # 动作裁剪上界
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [40.0, 40.0, 40.0,  # RL 控制 P 增益
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0,
          40.0, 40.0, 40.0]
  rl_kd: [1.0, 1.0, 1.0,  # RL 控制 D 增益
          1.0, 1.0, 1.0,
          1.0, 1.0, 1.0,
          1.0, 1.0, 1.0]
  fixed_kp: [60, 60, 60,  # 固定姿态控制 P 增益
             60, 60, 60,
             60, 60, 60,
             60, 60, 60]
  fixed_kd: [5, 5, 5,  # 固定姿态控制 D 增益
             5, 5, 5,
             5, 5, 5,
             5, 5, 5]
  num_of_dofs: 12
  action_scale: [0.25, 0.25, 0.25,  # 动作缩放
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0  # 线速度缩放
  ang_vel_scale: 0.25  # 角速度缩放
  dof_pos_scale: 1.0  # 关节位置缩放
  dof_vel_scale: 0.05  # 关节速度缩放
  commands_scale: [1.0, 1.0, 1.0]  # 指令缩放（保持与观测维度一致）
  torque_limits: [45.0, 45.0, 45.0,  # 力矩限制
                  45.0, 45.0, 45.0,
                  45.0, 45.0, 45.0,
                  45.0, 45.0, 45.0]
  default_dof_pos: [ 0.1000, 0.8000, -1.5000,  # 默认关节姿态（FL、FR、RL、RR）
                    -0.1000, 0.8000, -1.5000,
                     0.1000, 1.0000, -1.5000,
                    -0.1000, 1.0000, -1.5000]
  joint_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]  # 策略关节→电机映射
  gait_cycle_time: 0.5  # 相位周期
