# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0

go2/go2_jump:
  model_name: "policy_1.pt"
  num_observations: 47
  observations: ["zeros2", "commands", "ang_vel", "base_rpy", "dof_pos", "dof_vel", "actions"]
  observations_history: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
  observations_history_priority: "time"
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0,
          20.0, 20.0, 20.0]
  rl_kd: [0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5,
          0.5, 0.5, 0.5]
  fixed_kp: [60, 60, 60,
             60, 60, 60,
             60, 60, 60,
             60, 60, 60]
  fixed_kd: [5, 5, 5,
             5, 5, 5,
             5, 5, 5,
             5, 5, 5]
  num_of_dofs: 12
  action_scale: [0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25,
                 0.25, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [45.0, 45.0, 45.0,
                  45.0, 45.0, 45.0,
                  45.0, 45.0, 45.0,
                  45.0, 45.0, 45.0]
  default_dof_pos: [ 0.1000, 0.8000, -1.5000,
                    -0.1000, 0.8000, -1.5000,
                     0.1000, 1.0000, -1.5000,
                    -0.1000, 1.0000, -1.5000]
  joint_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]
